#!/bin/bash

NAME="TaxApp"
DIR=/home/jtb/TaxApp
USER=jtb
GROUP=jtb
WORKERS=4
BIND=unix:/home/jtb/run/gunicorn.sock
DJANGO_SETTINGS_MODULE=TaxApp.settings
DJANGO_WSGI_MODULE=TaxApp.wsgi
LOG_LEVEL=error

cd $DIR
source ../bin/activate
source .env

export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DIR:$PYTHONPATH

exec ../bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
    --name $NAME \
    --workers $WORKERS \
    --user=$USER \
    --group=$GROUP \
    --bind=$BIND \
    --log-level=$LOG_LEVEL \
    --log-file=../logs/gunicorn-error.log